#!/usr/bin/env python3
"""
Split all_primes.txt (one prime per line from primesieve) into
primes1.txt through primes50.txt in t5k.org format.

Each file: 2M primes, 10 per line, space-separated, with header.
"""

import sys
from pathlib import Path

PRIMES_PER_FILE = 2_000_000
PRIMES_PER_LINE = 10
NUM_FILES = 50
INPUT_FILE = Path(__file__).parent / "all_primes.txt"
OUTPUT_DIR = Path(__file__).parent


def split_primes(input_path: Path = INPUT_FILE, output_dir: Path = OUTPUT_DIR):
    print(f"Reading {input_path}...")

    with open(input_path, 'r') as f:
        file_num = 1
        primes_in_file = []
        total = 0

        for line in f:
            line = line.strip()
            if not line:
                continue
            prime = int(line)
            primes_in_file.append(prime)
            total += 1

            if len(primes_in_file) == PRIMES_PER_FILE:
                write_file(output_dir, file_num, primes_in_file)
                file_num += 1
                primes_in_file = []

                if file_num > NUM_FILES:
                    break

        # Write any remaining primes
        if primes_in_file and file_num <= NUM_FILES:
            write_file(output_dir, file_num, primes_in_file)

    print(f"Done. Total primes read: {total:,}")
    print(f"Files written: primes1.txt through primes{min(file_num, NUM_FILES)}.txt")


def write_file(output_dir: Path, file_num: int, primes: list):
    path = output_dir / f"primes{file_num}.txt"
    first = primes[0]
    last = primes[-1]

    with open(path, 'w') as f:
        f.write(f"The Primes from {first:,} to {last:,} (generated by primesieve)\n")

        for i in range(0, len(primes), PRIMES_PER_LINE):
            chunk = primes[i:i + PRIMES_PER_LINE]
            f.write(" ".join(str(p) for p in chunk) + "\n")

    n_lines = (len(primes) + PRIMES_PER_LINE - 1) // PRIMES_PER_LINE
    print(f"  primes{file_num}.txt: {len(primes):,} primes, "
          f"{n_lines:,} data lines, range [{first:,} .. {last:,}]")


if __name__ == "__main__":
    if len(sys.argv) > 1:
        split_primes(Path(sys.argv[1]))
    else:
        split_primes()
